version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
      - uploads:/var/www/uploads
    depends_on:
      - backend
      - frontend
    networks:
      - renovaai-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - DATABASE_URL=postgresql://renovaai:renovaai@postgres:5432/renovaai
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - renovaai-network
    restart: unless-stopped
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_BASE_URL=https://renova.andrius.cloud
    volumes:
      - frontend_build:/app/build
    networks:
      - renovaai-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=renovaai
      - POSTGRES_PASSWORD=renovaai
      - POSTGRES_DB=renovaai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - renovaai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U renovaai"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  uploads:
  frontend_build:
  postgres_data:

networks:
  renovaai-network:
    driver: bridge 